Repository ryuuganime/Ryuuganime, pull requests merged in 2020-01, with the labels that each got.

#4 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#5 Add HTMLProofer
  .github/workflow.yml
Labels: enhancement

#7 Ye asw
  lib/anime-db/2019/Fall/Assassins Pride.html
  lib/anime-db/2019/Fall/Beastars.html
  lib/anime-db/2019/Fall/Bokutachi wa Benkyou ga Dekinai!.html
  lib/anime-db/2019/Fall/Chihayafuru 3.html
  lib/anime-db/2019/Fall/Choujin Koukousei-tachi wa Isekai demo Yoyuu de Ikinuku you desu!.html
  lib/anime-db/2019/Fall/Hataage! Kemono Michi.html
  lib/anime-db/2019/Fall/High Score Girl II.html
  lib/anime-db/2019/Fall/Honzuki no Gekokujou_ Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen.html
Labels: library

#8 Tambah Informasi Tracker
  Assets/Providers/Trackers/README.md
Labels: documentation, library
